services:
  ffc-techspike-customer-registry-web:
    build:
      context: .
      target: production
    image: ffc-techspike-customer-registry-web
    container_name: ffc-techspike-customer-registry-web
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-techspike-customer-registry-web-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
      COOKIE_PASSWORD: who-likes-cookies-i-like-cookies-everybody-likes-cookies
      REDIS_HOSTNAME: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
